### ISSUE TITLE
Cannot call sendError() after the response has been committed 에러

### ISSUE THREAD

**Issue by bsh9254** [ever-rent/ever-rent-BE#17]
Cannot call sendError() after the response has been committed 에러 발생했습니다. 아마 연관관계 문제인 것 같습니다.

**Comment by Hiluxy** [comment]
해당오류는 JAVA에 Json타입 변환 과정 중 일어난 오류입니다. 무한참조 문제같네요.
Member와 products부분에서 문제가 생긴 것 같습니다. 한번 확인해보겠습니다.

**Comment by Hiluxy** [comment]
해당오류는 JAVA에 Json타입 변환 과정 중 일어난 오류입니다. 무한참조 문제같네요.
Member와 products부분에서 문제가 생긴 것 같습니다. 한번 확인해보겠습니다.
